openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Agendamento de pacientes'
  description: 'Documentação da API de agendamento de pacientes'
paths:
  /agendamentos:
    get:
      summary: 'Retorna os agendamentos de acordo com os filtros'
      operationId: getAgendamento
      description: ''
      parameters: 
        - in: query
          name: page
          description: 'Número da página da consulta'
          schema:
            type: number
        - in: query
          name: pagesize
          description: 'Tamanho da página da consulta'
          schema:
            type: number
        - in: query
          name: page
          description: 'Número da página da consulta'
          schema:
            type: number
        - in: query
          name: page
          description: 'Número da página da consulta'
          schema:
            type: number
        - in: query
          name: sortId
          schema:
            type: string
        - in: query
          name: sortDirection
          schema:
            type: string
            enum: 
            - ''
            - 'asc'
            - 'desc'
      responses:
        '200':
          description: 'Sucesso'
        '400':
          description: 'Faltam parâmetros obrigatórios ou eles não estão no formato correto'
    post:
      summary: 'Cadastra um agendamento no sistema'
      operationId: criaAgendamento
      description: ''
      responses:
        '201':
          description: 'Agendamento criado com sucesso'
        '400':
          description: 'Faltam parâmetros obrigatórios ou eles não estão no formato correto'
        '409':
          description: 'Existe um conflito de horários com esse paciente'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Atendimento'
        description: Atendimento que será registrado
  /agendamentos/{id}:
    get:
      summary: 'Retorna o agendamento com esse id no sistema'
      operationId: getAgendamento
      description: ''
      parameters: 
        - in: path
          name: id
          description: 'ID do atendimento'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Sucesso'
        '404':
          description: 'Não foi possível encontrar o agendamento no sistema'
    put:
      summary: 'Atualiza o agendamento com esse id no sistema'
      operationId: getAgendamento
      description: ''
      parameters: 
        - in: path
          name: id
          description: 'ID do atendimento'
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'Agendamento alterado com sucesso'
        '400':
          description: 'Faltam parâmetros obrigatórios ou eles não estão no formato correto'
        '404':
          description: 'Não foi possível encontrar o agendamento no sistema'
    delete:
      summary: 'Remove o agendamento com esse id no sistema'
      operationId: getAgendamento
      description: ''
      parameters: 
        - in: path
          name: id
          description: 'ID do atendimento'
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'Agendamento apagado com sucesso'
        '404':
          description: 'Não foi possível encontrar o agendamento no sistema'
components:
  schemas:
    Atendimento:
      type: object
      required:
        - data_hora_inicio
        - data_hora_fim
        - paciente
        - procedimento
      properties:
        data_hora_inicio:
          type: string
          format: date-time
        data_hora_fim:
          type: string
          format: date-time
        paciente:
          type: string
          example: 'Tomas Labella Menito'
        procedimento:
          type: string
          example: 'Atendimento simples'
    PagedResponse:
      type: object
      properties:
        content:
          type: array
        pageable:
          type: object
        totalPages:
          type: integer  
        totalElements:
          type: integer  
        last:
          type: boolean  
        size:
          type: integer  
        number:
          type: integer
        sort:
          type: object
          properties:
            unsorted:
              type: boolean
            sorted:
              type: boolean
        first:
          type: boolean
        numberOfElements:
          type: integer
servers:
  - description: 'default'
    url:  /api/