openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Agendamento de pacientes'
  description: 'Documentação da API de agendamento de pacientes'
paths:
  /agendamentos:
    get:
      summary: 'Retorna os agendamentos de acordo com os filtros'
      operationId: getAgendamento
      description: ''
      parameters: 
        - in: query
          name: search
          description: 'Filtro global por string'
          schema:
            type: string
        - in: query
          name: offset
          description: 'Número de items pulados na paginação'
          schema:
            type: integer
        - in: query
          name: limit
          description: 'Número de resultados da consulta'
          schema:
            type: integer
        - in: query
          name: sort
          description: 'Ordenação dos resultados'
          schema:
            type: string
            enum: 
            - 'data'
            - 'hora_fim'
            - 'hora_inicio'
            - 'data_hora_fim'
            - 'data_hora_inicio'
            - 'id'
            - 'paciente'
            - 'procedimento'
            - '-data'
            - '-hora_fim'
            - '-hora_inicio'
            - '-data_hora_fim'
            - '-data_hora_inicio'
            - '-id'
            - '-paciente'
            - '-procedimento'
      responses:
        '200':
          description: 'Sucesso'
        '400':
          description: 'Faltam parâmetros obrigatórios ou eles não estão no formato correto'
    post:
      summary: 'Cadastra um agendamento no sistema'
      operationId: criaAgendamento
      description: ''
      responses:
        '201':
          description: 'Agendamento criado com sucesso'
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                    format: integer
                  next:
                    type: string
                    format: url
                  previous:
                    type: string
                    format: url
                  results:
                    type: array
                    items:
                      type: object
                      $ref: '#/components/schemas/Atendimento'
        '400':
          description: 'Faltam parâmetros obrigatórios ou eles não estão no formato correto'
        '409':
          description: 'Existe um conflito de horários com esse paciente'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Atendimento'
        description: Atendimento que será registrado
  /agendamentos/{id}:
    get:
      summary: 'Retorna o agendamento com esse id no sistema'
      operationId: getAgendamento
      description: ''
      parameters: 
        - in: path
          name: id
          description: 'ID do atendimento'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Sucesso'
        '404':
          description: 'Não foi possível encontrar o agendamento no sistema'
    put:
      summary: 'Atualiza o agendamento com esse id no sistema'
      operationId: getAgendamento
      description: ''
      parameters: 
        - in: path
          name: id
          description: 'ID do atendimento'
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'Agendamento alterado com sucesso'
        '400':
          description: 'Faltam parâmetros obrigatórios ou eles não estão no formato correto'
        '404':
          description: 'Não foi possível encontrar o agendamento no sistema'
    delete:
      summary: 'Remove o agendamento com esse id no sistema'
      operationId: getAgendamento
      description: ''
      parameters: 
        - in: path
          name: id
          description: 'ID do atendimento'
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'Agendamento apagado com sucesso'
        '404':
          description: 'Não foi possível encontrar o agendamento no sistema'
components:
  schemas:
    Atendimento:
      type: object
      required:
        - data_hora_inicio
        - data_hora_fim
        - paciente
        - procedimento
      properties:
        data_hora_inicio:
          type: string
          format: date-time
        data_hora_fim:
          type: string
          format: date-time
        paciente:
          type: string
          example: 'Tomas Labella Menito'
        procedimento:
          type: string
          example: 'Atendimento simples'
servers:
  - description: 'default'
    url:  /api/