# Generated by Django 2.0.1 on 2018-01-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('paciente', models.CharField(max_length=200)),
                ('procedimento', models.CharField(max_length=200)),
            ],
        ),
    ]
